name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, macos]
        arch: [arm64, amd64, 386]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      working-directory: src
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o proxytest-${{ matrix.os }}-${{ matrix.arch }}
