name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Change workdir
      run: cd src

    - name: Set Go env
      run: go env -w GO111MODULE=on

    - name: Build
      run: go build ./main.go
